<!--set params-->
<?php $url=URL.'/product/index/page/';?>
<?php $limit        = $controller->getSessParam('limit'); ?>
<?php $orderType    = $controller->getSessParam('ordertype'); ?>
<?php $orderBy      = $controller->getSessParam('orderByProduct'); ?>
<?php $category      = $controller->getSessParam('category'); ?>
<?php $currentPage  = $view->getParam('currentPage'); ?>
<?php $products     = $view->getParam('products'); ?>

<?php if(!empty($products)) :?>

          
<div class="row">
    <div class="col-md-6">
        <h2  class="mainBox">Наши продукты</h2>
    </div>
    <div class="col-md-2">
            <!--include limit for items-->
            <?php include SITE_PATH.DS.'View'.DS.'limit.phtml';?>
    </div>
    <div class="col-md-2">
            <!-- menu for sort-->
            <div class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    Сортировать по:
                    <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li>
                        <a href='<?= $url.$currentPage;?>/orderby/name'>Имени<?php if($orderBy == 'name') :?>&#9668;<?php endif; ?>
                    </li>
                    <li>
                       <a href='<?= $url.$currentPage;?>/orderby/price'>Цене<?php if($orderBy == 'price') :?>&#9668;<?php endif; ?></a>
                    </li>
                    <li>
                        <a href='<?= $url.$currentPage;?>/orderby/total'>Количеству<?php if($orderBy == 'total') :?>&#9668;<?php endif; ?></a>
                    </li>               
                </ul>
            </div>
    </div>
    <div class="col-md-2">
            <div class="Title">
                <div><a href='<?= $url.$currentPage;?>/ordertype/asc'>по возрастанию<?php if($orderType == 'asc') :?>&#9650;<?php endif; ?></a></div>
                <div><a href='<?= $url.$currentPage;?>/ordertype/desc'>по убыванию<?php if($orderType == 'desc') :?>&#9660;<?php endif; ?></a></div> 
            </div>
    </div>         .
</div>

        <div class="row">
            <div class="col-md-2">
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav nav-pills">
                        <li <?php if($category=='1'):?>class="active"<?php endif;?>>
                            <a href="<?php echo URL;?>/product/index/category/1">Велосипеды</a>
                        </li>
                        <li <?php if($category=='2'):?>class="active"<?php endif;?>>
                            <a href="<?php echo URL;?>/product/index/category/2">Ролики</a>
                        </li>
                        <li <?php if($category=='3'):?>class="active"<?php endif;?>>
                            <a href="<?php echo URL;?>/product/index/category/3">Скейты</a>
                        </li>
                        <li <?php if($category=='4'):?>class="active"<?php endif;?>>
                            <a href="<?php echo URL;?>/product/index/category/4">Коньки</a>
                        </li> 
                        <li <?php if($category=='5'):?>class="active"<?php endif;?>>
                            <a href="<?php echo URL;?>/product/index/category/5">Лыжи</a>
                        </li> 
                        <li <?php if($category=='6'):?>class="active"<?php endif;?>>
                           <a href="<?php echo URL;?>/product/index/category/6">Сноуборды</a>
                        </li>
                    </ul>
                </div>
            </div>

            <div class="col-md-8">
            <!--include pagination-->
            <?php 
            $countPages = ceil($view->getParam('countProducts') / $limit);
            if($countPages>1){include SITE_PATH.DS.'View'.DS.'paginator.phtml';}
            ?>
            <!--print items-->
                <?php foreach($products as $product) : ?>
                <?php
                    $src    = URL.'/img/img.png';
                    $imgUrl =('/img/Products/'.$product->category.'/'.$product->img);           
                    if($product->img != NULL && is_readable(SITE_PATH.$imgUrl)){$src = URL.$imgUrl;}        
                ?>
                <div id="product" class="row bg-info"> 
                    <div class="col-md-3">
                        <a class="gallery"  title="<?=$product->name?>" href="<?=$src?>"><img class="img-circle" height="150" alt="<?='img-'.$product->img;?>" src="<?=$src?>"></a>     
                    </div>
                    <div class="col-md-3">
                        <label>     Описание</label>
                        <div><?= $product->description;?></div> 
                    </div>
                    <div class="col-md-4">
                       <div class="col-md-4" >
                                </br>
                                <div>Название:</div>      
                                <div>Цена:</div>
                                <div>Кол-во:</div>
                            </div>
                            <div class="col-md-8">
                                </br>
                                <div><a href="<?=URL.'/product/productInfo/page/'.$currentPage.'/id/'.$product->id?>"><?= $product->name;?> </a> </div>
                                <div><?= $product->price;?></div>
                                <div><?= $product->total;?></div>
                                </br>
                                <a href="<?=URL.'/product/productInfo/page/'.$currentPage.'/id/'.$product->id?>" class="btn btn-primary btn-lg text-right" role="button">Выбрать</a>
                            </div>
                    </div>
                  </div><br/>
                <?php endforeach; ?>
            <!--include pagination-->
            <?php 
            if($countPages>1){include SITE_PATH.DS.'View'.DS.'paginator.phtml';}
            ?>
            
            
            </div>
        </div>
</div>



<?php  elseif($view->getParam('error')) : ?>
    <div style="color:red;"><h1><?php echo $view->getParam('error')?></h1></div>
<?php endif; ?>