
<!--set params-->
<?php   
$product     = $view->getParam('product');
$currentPage  = $view->getParam('currentPage');
$url=URL.'/product/index/page/'.$currentPage;
$src    = URL.'/img/img.png';
$id='';
if(!empty($product))
    {
    $id='/id/'.$product->id;
    $name=$product->name;
    $description = $product->description;
    $price= $product->price;
    $total= $product->total;
    $imgUrl =('/img/Products/'.$product->category.'/'.$product->img);        
    if($product->img != NULL && is_readable(SITE_PATH.$imgUrl)){$src = URL.$imgUrl;}    
    }      
?>

<!--form for insert(update) product-->
<div class="text-center bg-info col-md-4 col-md-offset-4" id="body">
<div class="error"><?=$errorMessage?></div>
<form action="<?=$url.$id.'/bye/1'?>" method="POST">
    <br/>
    <div>
        <img class="img-polaroid" height="300px" alt="<?='img-'.$product->img;?>" src="<?=$src?>">
   
    </div>
    <div id="forLabel">    
        <div class="row">
            <div class="col-md-4 col-md-offset-2">
                <label for="name">Название</label>
            </div>
            <div class="col-md-4">
                <?=$name?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4 col-md-offset-2">
                <label for="price">Цена</label>
            </div>
             <div class="col-md-4">
                <?=$price?>
             </div>
        </div>
        <div class="row">
            <div class="col-md-4 col-md-offset-2">
                <label for="quantity">Количество</label>
            </div>
            <div class="col-md-4">
                <input type="number" name="quantity" id="quantity" value="1">
            </div>
        </div>
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
            <label for="description">Описание</label>
            </div>
        </div>
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <?=$description?>
            </div>
        </div>
    </div>
  <div>
        <input  type="submit" value="Bye">
        <a href="<?=$url?>" class="btn btn-primary btn-sm text-right" role="button">Cansel</a>
  </div>
</form>
</div>