<?php
/**
 * @var Model_User $user
 */
$user = $view->getParam('user');

?>
<?php if($user) : ?>

<!--set params-->
<?php 
    $src = URL.'/img/img.png';
    $imgUrl =('/img/Users/'.$user->photo);        
    if($user->photo != NULL && is_readable(SITE_PATH.$imgUrl)){$src = URL.$imgUrl;}
?>
<br/>
<!--show user profile-->
<form>
<div class="col-md-6 col-md-offset-3">
<div class="row" id="body">
    <div class=" col-md-5">
        <img height="200px" alt="photo-<?=$user->login;?>" src="<?=$src?>"> 
    </div>
    <div class="col-md-2" id="forLabels">
        <label for="login">login :</label>
        <label for="email">email :</label>
        
    </div>    
    <div class="col-md-4" id="userInfo">
        
        <input type="text" name="login" id="login" value="<?=!empty($user->login) ? $user->login : '';?>" placeholder="login">
        <input type="email" name="email" id="email" value="<?=!empty($user->email) ? $user->email : '';?>" placeholder="eMail">
        
    </div>    
</div>
    <div class="row text-center">
        <input type="submit" value="Ok">
        <input type="reset" value="Отмена">
    </div>    
</div>
</form>

<?php  elseif($view->getParam('error')) : ?>
    <div style="color:red;"><h1><?php echo $view->getParam('error')?></h1></div>
<?php endif; ?>