<!--check error-->
<?php
$errorType = $view->getParam('error');
$errorMessage = '';
    if(!empty($errorType)) {
        switch($errorType) {
            case System_Exception::INVALID_LOGIN:
                $errorMessage = 'User not found';
                break;
            case System_Exception:: NOT_FOUND:
                $errorMessage = 'Product not found';
                break;
            case System_Exception::VALIDATE_ERROR:
                $errorMessage = 'uncorect date';
                break;
            default : $errorMessage=$errorType;
        }
    }?>

<!--set params-->
<?php   
$order     = $view->getParam('order');
$currentPage  = $view->getParam('currentPage');
$url=URL.'/Admin/order';

if(!empty($order))
    {
    $url.='/id/'.$order->id;
    $user=$order->modelUser;
    $date = $order->date;
    $amount= $order->amount;
    $products= $order->orderItems;
    }      
?>

<!--form for insert(update) order-->
<div class="col-md-4 col-md-offset-4" id="body">
    <br />
<div class="bg-danger text-center"><?=$errorMessage?></div>
<form action="<?=$url.'/page/'.$currentPage.'/set/1'?>" method="POST" enctype="multipart/form-data">
    
    <div id="forInput">
    <label for="email">eMail</label>   
    <input type="text" name="email" id="name" value="<?=$user->email?>"placeholder="eMail"> 
    </div>  
    <div>
    <label for="date">Дата</label> 
    <input type="date" name="date" id="date" value="<?=$date?>"placeholder="Date">
    </div> 
    <h4>products</h4> 
    <a id="add" href="#" class="btn btn-primary btn-sm text-right" role="button">Добавить продукт</a>
    
    <div id="products">
        <br />
        <?php if(empty($products)):?>
        <div>
            <label name="1">1</label>
            <input type="text" name="product1" id="product1" placeholder="Product">
            <input type="number" name="quantity1" id="quantity1" placeholder="quantity">
        </div>
        <?php else:?>
            <?php
            $i=0;
            foreach ($products as $item):?>
                  
                <?php ++$i;?>
               <div>
                    <label name="<?=$i?>"><?=$i?></label>
                    <input type="text" name="product<?=$i?>" id="product<?=$i?>" value="<?=$item->modelProduct->name?>">
                    <input type="number" name="quantity<?=$i?>" id="quantity<?=$i?>" value="<?=$item->quantity?>">
               </div>
                <?php endforeach;?>
        <?php endif;?>
    </div>  
    <br />
    <div>
        <input type="submit" class="btn btn-primary" value="Ok">
        <input type="reset" class="btn btn-primary" value="Сброс">
        <a href="<?=URL.'/Admin/order'.'/page/'.$currentPage?>" class="btn btn-primary" role="button">Отмена</a>
    </div>
</form>
</div>