<!--include admin menu-->
<?php include 'menu.phtml';?>

<!-- set params -->
<?php $url=URL.'/admin/order/page/';?>
<?php $limit        = $controller->getSessParam('limit'); ?>
<?php $orderType    = $controller->getSessParam('ordertype'); ?>
<?php $orderBy      = $controller->getSessParam('orderByOrder'); ?>
<?php $currentPage  = $view->getParam('currentPage'); ?>
<?php $orders     = $view->getParam('orders'); ?>
<!--include limit for items-->
<?php include SITE_PATH.DS.'View'.DS.'limit.phtml';?>

<h2 class="mainBox">ADmin продукты</h2>
<h3><a href="<?=URL.'/admin/productInfo'?>">Добавить новый</a></h3>

<!-- menu's for sort-->
<?php if(!empty($orders)) :?>
    <table align="center">
        <tr>
            <th></th>
            <?php if($orderType == 'asc') : ?>
                <th><a href='<?php echo $url.$currentPage;?>/orderby/img/ordertype/desc'>userId<?php if($orderBy == 'img') :?>&darr;<?php endif; ?></a></th>
                <th><a href='<?php echo $url.$currentPage;?>/orderby/name/ordertype/desc'>date<?php if($orderBy == 'name') :?>&darr;<?php endif; ?></a></th>
                <th><a href='<?php echo $url.$currentPage;?>/orderby/name/ordertype/desc'>amount<?php if($orderBy == 'description') :?>&darr;<?php endif; ?></a></th>                
            <?php else : ?>
                <th><a href='<?php echo $url.$currentPage;?>/orderby/img/ordertype/asc'>userId<?php if($orderBy == 'img') :?>&uarr;<?php endif; ?></a></th>
                <th><a href='<?php echo $url.$currentPage;?>/orderby/name/ordertype/asc'>date<?php if($orderBy == 'name') :?>&uarr;<?php endif; ?></a></th>
                <th><a href='<?php echo $url.$currentPage;?>/orderby/name/ordertype/asc'>amount<?php if($orderBy == 'description') :?>&uarr;<?php endif; ?></a></th>                
            <?php endif; ?>  
               <th></th>  
        </tr> 
        
<!-- print items-->   
    <?php foreach($orders as $order) : ?>    
    <tr>   
        <td><a href="<?=URL.'/admin/orderInfo/page/'.$currentPage.'/id/'.$order->id?>">change</a></td>
        <td class="mainBox"><?php echo $order->modelUser->email;?></td>
        <td class="mainBox"><?php echo $order->date;?></td>
        <td class="mainBox"><?php echo $order->amount;?></td>
       
        <td><a href="<?=URL.'/admin/remove/action/order/page/'.$currentPage.'/id/'.$order->id?>">delete</a></td>
    </tr>
        <?php endforeach; ?>   
</table>

<!--include pagination-->
    <?php 
    $countPages = ceil($view->getParam('countProducts') / $limit);
    if($countPages>1){include SITE_PATH.DS.'View'.DS.'paginator.phtml';}
    ?>

<?php endif; ?>