<?php
$currentPage  = $view->getParam('currentPage');
$id = $view->getParam('id');
$action=$view->getParam('action');
str_replace($id,'_', '/');
$url=URL.'/admin/'.$action.'/page/'.$currentPage;
?>
<br/>
<div class="bg-danger text-center col-md-4 col-md-offset-4" id="remove">
    
    <h2>Вы действительно хотите удалить запись?</h2>
    <a href="<?=$url.'/remove/1'.'/id/'.$id?>" class="btn btn-primary btn-sm text-right" role="button">Да!</a>
    <a href="<?=$url?>" class="btn btn-primary btn-sm text-right" role="button">Отменить</a>
</div>
