            <br/>
            <div class="row" align="center">
                <div class="col-md-3">
                    <a href="<?php echo URL;?>/product/index/category/1"><img src="<?=URL?>/img/Category/bicycle.png"></a> 
                     <a href="<?php echo URL;?>/product/index/category/1"><h3>Велосипеды</h3></a>
                </div>
                <div class="col-md-3">
                    <a href="<?php echo URL;?>/product/index/category/2"><img src="<?=URL?>/img/Category/roller.png"></a>
                    <a href="<?php echo URL;?>/product/index/category/2"><h3>Ролики</h3></a>
                </div>
                <div class="col-md-3">
                    <a href="<?php echo URL;?>/product/index/category/3"><img src="<?=URL?>/img/Category/skateboard.jpg"></a>
                    <a href="<?php echo URL;?>/product/index/category/3"><h3>Скейты</h3></a>
                </div>                
            </div>
            <br/>
            <div class="row" align="center">
                <div class="col-md-3">
                    <a href="<?php echo URL;?>/product/index/category/4"><img src="<?=URL?>/img/Category/skates.jpg"></a> 
                    <a href="<?php echo URL;?>/product/index/category/4"><h3>Коньки</h3></a>
                </div>
                <div class="col-md-3">
                    <a href="<?php echo URL;?>/product/index/category/5"><img src="<?=URL?>/img/Category/ski.jpg"></a> 
                    <a href="<?php echo URL;?>/product/index/category/5"><h3>Лыжи</h3></a>
                </div>
                <div class="col-md-3">
                    <a href="<?php echo URL;?>/product/index/category/6"><img src="<?=URL?>/img/Category/snowboard.jpg"></a>
                    <a href="<?php echo URL;?>/product/index/category/6"><h3>Сноуборды</h3></a>
                </div>                
            </div>