            <br/>
            <div class="row" align="center">
                <div class="col-md-3">
                    <a href="<?php echo URL;?>/product/index/category/1"><img src="<?=URL?>/img/img.png"></a> 
                    <h3>first</h3>
                </div>
                <div class="col-md-3">
                    <a href="<?php echo URL;?>/product/index/category/2"><img src="<?=URL?>/img/img.png"></a>
                    <h3>second</h3>
                </div>
                <div class="col-md-3">
                    <a href="<?php echo URL;?>/product/index/category/3"><img src="<?=URL?>/img/img.png"></a>
                    <h3>3</h3>
                </div>                
            </div>
            <br/>
            <div class="row" align="center">
                <div class="col-md-3">
                    <a href="<?php echo URL;?>/product/index/category/4"><img src="<?=URL?>/img/img.png"></a> 
                    <h3>4</h3>
                </div>
                <div class="col-md-3">
                    <a href="<?php echo URL;?>/product/index/category/5"><img src="<?=URL?>/img/img.png"></a> 
                    <h3>5</h3>
                </div>
                <div class="col-md-3">
                    <a href="<?php echo URL;?>/product/index/category/6"><img src="<?=URL?>/img/img.png"></a>
                    <h3>6</h3>
                </div>                
            </div>