<?php 
    $userId = $controller->getUserId();
          
    $userRoleId = 0;
    if($userId) {
        $userModel      = Model_User::getById($userId);
        $userEmail      = $userModel->email;
        $userRoleId     = $userModel->role_id; 
    }

    $errorType = $controller->getParamByKey('error');
    $errorMessage = '';
    if(!empty($errorType)) {
        switch($errorType) {
            case System_Exception::ALREADY_EXIST:
                $errorMessage = 'Such account already exists!';
                break;
            case System_Exception::VALIDATE_ERROR:
                $errorMessage = 'Invalid enetered data!';
                break;
            case System_Exception::ERROR_CREATE_USER:
                $errorMessage = 'Can\'t create new user! Try again!';
                break;
            case System_Exception::INVALID_LOGIN:
                $errorMessage = 'Invalid user or password!';
                break;    
        }
    } 
?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">        
        <title><?php echo $_SERVER['SERVER_NAME'];?></title>
        
        <link href="<?= URL; ?>/Bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
<!--        <link href="<?= URL.'/css/'.$viewFolder.'/'.$actionName.'.css'; ?>" rel="stylesheet" type="text/css"/>-->
        
        <!-- add lquery-->
        <script type="text/javascript" src="<?= URL;?>/fancybox/lib/jquery-1.10.1.min.js"></script> 
        
        <!-- Add mousewheel plugin (this is optional) -->
        <script type="text/javascript" src="<?= URL?>/fancybox/lib/jquery.mousewheel-3.0.6.pack.js"></script>

        <!-- Add fancyBox -->
        <link rel="stylesheet" href="<?= URL?>/fancybox/source/jquery.fancybox.css?v=2.1.5" type="text/css" media="screen" />
        <script type="text/javascript" src="<?= URL?>/fancybox/source/jquery.fancybox.pack.js?v=2.1.5"></script>
        
        <script type="text/javascript" src="<?= URL;?>/js/authorize.js"></script>
        <script type="text/javascript" src="<?= URL.'/js/'.$viewFolder.'/'.$actionName.'.js'?>"></script>
    </head>    
    <body class="container">
     <br/>   
        <div class="row"> 
            <div id="error" class="col-md-6 text-danger text-center"><?=$errorMessage?></div>
            <div class="col-md-6">
                <div <?= !empty($userId) ?'':'style="display: none;"';?> class="row" id="userEnter">
                    <div id="userEmail" class="col-md-6">Вы зашли как : <a href="<?=URL?>/user/profile/id/<?=$userId?>"><?php echo !empty($userEmail) ? $userEmail : ''; ?></a></div>
                    <div id="userId" class="col-md-1"><a id="logout" href="#"><?php echo !empty($userId) ? 'Exit' : ''?></a></div>    
                </div>
                <div <?=!empty($userEmail)? 'style="display: none;"':''?> id="loginFormDiv">
                    <form name="autorize" id="loginForm" method="POST" autocomplete="off">
                        <input placeholder="eMail" type="text" name="email" maxlength="20" />
                        <input placeholder="Password" type="password" name="password" maxlength="30" />
                        <input id="save_checkbox" type="checkbox" name="save" value="1" /><label for="save_checkbox">Save</label>
                        <input type="submit" name="login" value="Enter" />
                        <input type="submit" name="register" value="Register" />
                    </form>
                </div>
            </div>            
        </div>   
       
                <div id="menu" class="mainBox">
                <ul class="nav nav-tabs">
                    <li <?php if($viewFolder=='Index'):?>class="active"<?php endif;?>>
                        <a href="<?php echo URL;?>/">Главная </a></li>
                    <li <?php if($actionName=='about'):?>class="active"<?php endif;?>>
                        <a href="<?php echo URL;?>/company/about">О компании </a></li>
                    <li <?php if($actionName=='contact'):?>class="active"<?php endif;?>>
                        <a href="<?php echo URL;?>/company/contact">Контакты </a></li>
                    <li <?php if($viewFolder=='Basket'):?>class="active"<?php endif;?>>
                        <a href="<?php echo URL;?>/basket" class="glyphicon glyphicon-shopping-cart"> Корзина </a></li> 
                    <li <?php if($viewFolder=='Admin'):?>class="active"<?php endif;?>>
                        <a id="admin_href" href="<?php echo URL;?>/admin/index" <?php if($userRoleId != Model_User::ROLE_ADMIN_ID) { echo 'style="display: none;"'; } ?>>Админка </a></li>
                </ul>
                </div> 
   
                <div id="forContent">
                <?php
                    if(file_exists($viewFileName)) {
                        include $viewFileName;
                    }
                ?>
                </div>
            <script src="<?= URL;?>/Bootstrap/js/bootstrap.min.js"></script> 
            
        
    </body>
    
</html>