            <div class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    Записей на стр:
                    <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li>
                        <a href='<?= $url.'1';?>/limit/3'>3 записей<?php if($limit == '3') :?>&#9668;<?php endif; ?></a>
                    </li>
                    <li>
                        <a href='<?= $url.'1';?>/limit/5'>5 записей<?php if($limit == '5') :?>&#9668;<?php endif; ?></a>
                    </li>
                    <li>
                        <a href='<?= $url.'1';?>/limit/10'>10 записей<?php if($limit == '10') :?>&#9668;<?php endif; ?></a>
                    </li>
                    <li>
                        <a href='<?= $url.'1';?>/limit/15'>15 записей<?php if($limit == '15') :?>&#9668;<?php endif; ?></a>
                    </li>
                    <li>
                        <a href='<?= $url.'1';?>/limit/20'>20 записей<?php if($limit == '20') :?>&#9668;<?php endif; ?></a>   
                    </li>
                </ul>
            </div>
