<?php 
// Params
  $countShowPages = 6;
  $halfShowPages=floor($countShowPages / 2);
    $left = $currentPage - 1;
    $right = $countPages - $currentPage;
    if ($left < $halfShowPages) $start = 1;
    else $start = $currentPage - $halfShowPages;
    $end = $start + $countShowPages - 1;
    if ($end > $countPages) {
      $start -= ($end - $countPages);
      $end = $countPages;
      if ($start < 1) $start = 1;
    }
?>
  <!-- print Pagination -->
  <div id="pagination">
      <div class="row">
          <div class="col-md-4">
              <ul class="pager">
                <?php echo $currentPage==1?'<li class="previous disabled"><a href="#">Предыдущая</a></li>':'<li><a href="'.$url.($currentPage - 1).'" title="Предыдущая страница">Предыдущая</a></li>';?>
              </ul>
          </div>
          <div class="col-md-4">
              <ul class="pagination">
                <?php if ($left > $halfShowPages): ?>      
                    <li><a href="<?=$url.'1'?>" title="Первая страница">1...</a></li>
                <?php endif; ?>
                <?php for ($i = $start; $i <= $end; $i++): ?>
                    <?php echo $i == $currentPage ? '<li class="active"><a href="#">'.$i.'</a></li>':'<li><a href="'.$url.$i.'">'.$i.'</a></li>';?>
                <?php endfor; ?>
                <?php if ($right >$halfShowPages): ?>      
                    <li><a href="<?=$url.$countPages?>" title="Последняя страница">...<?=$countPages?></a></li>     
                <?php endif; ?>
              </ul>
          </div>
          <div class="col-md-4">
              <ul class="pager">
                <?php echo $currentPage==$countPages?'<li class="previous disabled"><a href="#">Следующая</a></li>':'<li><a href="'.$url.($currentPage + 1).'" title="Следующая страница">Следующая</a></li>';?>
              </ul>
          </div>
      </div>
  </div>