<?php?>
<!--form for customer info-->
<br/>
<form action="<?=URL.'/basket/buy/complet/ok'?>">    
    <div class="row">
        <div class="col-md-1 col-md-offset-4">
            <label>eMail</label>
        </div>
        <div class="col-md-3">
            <input type="email" value="<?php echo !empty($userEmail) ? $userEmail : ''; ?>">
        </div>
    </div>
    <div class="row">
        <div class="col-md-1 col-md-offset-4">
           <label>Адрес</label>
        </div>
        <div class="col-md-3">
            <input type="text"> 
        </div>
    </div>
    <div class="row">
        <div class="col-md-1 col-md-offset-4">
           <label>Телефон</label>
        </div>
        <div class="col-md-3">
          <input type="number">
        </div>
    </div>
    <br/>
    <div class="row text-center">
        <input type="submit" value="ok">
        <input type="reset" value="reset">
    </div>
</form>
